### ISSUE TITLE
Mail contributor week brainstorming ideas

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/mail#10194]
- [x] ✔️✔️✔️✔️✔️ More discoverable multi-select and bulk operations  https://github.com/nextcloud/mail/issues/10231
- [x] ✔️✔️✔️✔️ Very slow and flaky syncing https://github.com/nextcloud/mail/issues/8223
- [x] ✔️✔️✔️ https://github.com/nextcloud/mail/issues/10386
- [x] ✔️✔️✔️ Enable routing of certain types of emails emails directly to a folder (like work reports). GUI for sieve filters  https://github.com/nextcloud/mail/issues/44
- [x] ✔️✔️✔️ Emails that were moved to a folder are still displayed in the inbox. Deleted emails should stay deleted. -> Improve caching system. Several people stopped using mail because of this.  https://github.com/nextcloud/mail/issues/9168 
- [ ] ✔️✔️ Create tasks in deck from emails  https://github.com/nextcloud/mail/issues/5900
- [ ] ✔️✔️ Enable markdown by default  
- [ ] ✔️ Don’t loose formatting upon copy paste (e.g. notes to mail)  
- [ ] ✔️ Quick filters missing close to the search bar (unread, favourites)  
- [ ] ✔️ Improve counters calculations and placements 0(230)  
- [ ] ✔️ Collapse mailboxes in the sidebar  
- [ ] ✔️ Auto delete spam  
- [ ] ✔️ Preloading email body for faster viewing  
14. There’s no unread marker in threads  
15. Shared mailbox or folders  
16. Setting mail reminders  
17. Preview upon hovering attachments  
18. Small mail editor bottom right that doesn’t block the interface  
19. Real search (not only subject and people)  
20. Tags in navigation  
21. Collapse previous messages in replies  
22. Alert to respond to important emails  
23. Auto mark emails in folders as read  
24. Auto add flights and hotel bookings to calendar (it’s there but not visible enough)  
25. New message composer fullscreen  
26. Setting priorities for mail from important people  
27. relocate action buttons (move to the bottom / sticky)  
28. Associate folders with mailing lists  
29. Calendar events embedding  
30. Spam filter that works  
31. Restrict closing tab while undo send is available  
32. Mail action menu is not intuitive, difficult to scan, condense action menu in the same menu  
33. Improve empty content when opening mail app  
34. Recipients are missing in each email in threads  
35. Delete email option inline in the wide view

FYI @ChristophWurst @jancborchardt @nimishavijay

**Comment by marcoambrosini** [comment]
@ChristophWurst could you please work with your team to link existing issues to each item and or create new ones if you think it's needed?

**Comment by ChristophWurst** [comment]
I appreciate the feedback @LostinSpacetime! Finding the right priority is tricky as everyone has different needs. The result above are based on a group of randomly selected people that use Nextcloud daily. Perhaps @marcoambrosini can add some context to the ticket description for the people who did not participate.

**Comment by Aveyron-RetD** [comment]
Number 2 and 5 should be solved with the newly landed commits ❤️.

**Comment by ChristophWurst** [comment]
> More discoverable multi-select and bulk operations

@marcoambrosini @nimishavijay do you have ideas or suggestions for a more discoverable UI? Should we show the checkboxes all the time?

**Comment by marcoambrosini** [comment]
I think we should yes @ChristophWurst

**Comment by BiglifeMatt** [comment]
The areas that still prevent us from adopting this over SnappyMail:
1) Search... it never returns, just times out trying to retrieve any data (Can't load inbox)
2) Sieve settings do not have a user friendly setup.
3) The ability to respond to inline calendar requests from outside email such as Google calendar requests from external users.

**Comment by alexanderdd** [comment]
Hello, 

Maybe do some **user testing** during contributor week? Find a volunteer or maybe NC employee, let them work with Mail, screengrab the whole work day? I would be up for it but would have to check internally beforehand.

### Issues

I would be very happy if you can consider one of these issues for the contributer week:

1. One of the things that I miss the most is a **search** that finds what I want. Example:I just entered "keyword" in the search bar, open advanced search, click unread - it does not show me the email (that I know exists) that is unread and has "keyword" in both the sender adress and in the subject. 
2. this bugs me every week when I copy something from Text to Mail https://github.com/nextcloud/mail/issues/9858
3. this is pretty important usability IMO https://github.com/nextcloud/mail/issues/9215
5. also mailto: links are shown as suspicious links, should not be the case: "href: mailto:XY@example.com : link text <XY@example.com> "This is on cloud.nextcloud.com.

Thank you for working on this! 🚀

**Comment by ChristophWurst** [comment]
Closing as resolved. The top five items have been delivered. New brainstorming and rating will be done in the future. Thank you.
