### ISSUE TITLE
Show email summary in the thread list

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#10387]
### Is your feature request related to a problem? Please describe.

As a Nextcloud user I want to get a quick overview of my inbox emails without having to open them. There is a text preview, but it's use is limited. Most emails show *Hi Christoph …* and similar.

### Describe the solution you'd like

Process the email and give a concise summary instead of the literal text preview. Moreover, make the text two-lined, so I can get a bit more information out of the entry.

Show an icon in front of the generated text to make it clear that it's generated and not content of the sender.

### Work packages

- [ ] Make the preview text two-lined. This can also be done without https://github.com/nextcloud/mail/issues/10388.
- [ ] Show the generated summary instead of the preview text, if available.

### Additional context

- [ ] Requires https://github.com/nextcloud/mail/issues/10388
