### ISSUE TITLE
Snooze mails

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/mail#2048]
## Feature Request
To keep the inbox clean and clear it would be nice to snooze mails for x hours or y days.
Often the inbox is a kind of todo list. So if you can't do the todo right now you can snooze it for later.
Of I you send an importand mail you will keep track of it. So you can snooze the send mail and it will apear in the future, so you can ask about the status or send the demand again. 

## Summary
snozze a mail and move it automaticly back to the inbox after the choosen snozze time has expired

- [x] Requires https://github.com/nextcloud/mail/issues/3664

## Work packages

* [x] ~~Shallow prototype (in case MVP is not doable for feature freeze https://github.com/nextcloud/groupware/issues/70)~~
  * [x] ~~Add an action for *Snooze* to messages but only temporarily remove the message in the frontend~~
* [x] MVP
  * Add action *Snooze* with a few simple time ranges that moves the selected message to a dedicated "Snoozed" mailbox. System saves the timestamp until when the messages is snoozed.
  * Background job watches messages in Snoozed/Later and moves them back to INBOX when the time expires (source mailbox before snooze is not saved)
  * Message moved back to INBOX is sorted as usual (not yet at the top)
  * ~~Nextcloud notification for expired snoozes~~
* [x] Snoozed mailbox created at first use. Mailbox name is localized in UI. https://github.com/nextcloud/mail/issues/8742
* [x] ~~More detailed time ranges via a custom date picker~~ part of the mvp
* [x] https://github.com/nextcloud/mail/issues/8745
* [x] ~~Sort message back to the top~~ will not be done
* [x] https://github.com/nextcloud/documentation/issues/10968
* [x] https://github.com/nextcloud/mail/issues/8758
* [x] https://github.com/nextcloud/mail/issues/8763

## Follow-ups
* Move messages back to their original mailbox (not the INBOX) https://github.com/nextcloud/mail/issues/8779
* https://github.com/nextcloud/mail/issues/8744
* https://github.com/nextcloud/mail/issues/8746
* Interoperability
  * Look into options to make the Snooze/Later mailbox discoverable for us and other clients with a dedicated IMAP attribute similar to `\sent`, `\draft`, etc.
  * Look into options to push the snooze time to IMAP for other clients to read

**Comment by ChristophWurst** [comment]
This requires us to store more of the IMAP state locally.

**Comment by szaimen** [comment]
Maybe you could do it  the way Microsoft is doing it in Outlook on Android: 
If you use the snooze button the first time, you get a popup in which you get asked for defining an imap-folder for snoozed mails. So if snoozing mails, they get moved into this folder. And if I understood it correctly, the information until when it reappers inside you inbox is stored locally on your imap client, which is perfect for this usecase, because nextcloud mail is running on a server. The only downside is, that you cannot see this snoozing (or the day until it reappers inside your inbox) inside other imap-clients.

**Comment by jakobroehrl** [comment]
Here is how Kapano solves it.
You can add reminders to mails. This could be shown in the calendar and generate notifications:
![grafik](https://user-images.githubusercontent.com/24530680/66026357-f4b47400-e4f8-11e9-94d1-d5a380174b7a.png)

**Comment by Friptick** [comment]
Been looking for this since forever. Follow-up, reminder, snooze, whatever it takes. Just make the message go away for _x_ days. As OP says, many (probably most) people treat their inbox as a kind of to-do list. Incidentally, the snooze feature is a crucial part of the Inbox Zero and Getting Things Done methodologies, not to mention just being common sense.

Sorry to pile on without more specific information, but I was ready to post a new issue with what @jakobroehrl said, to the word. Which suggests that there might be latent demand for this feature.

**Comment by ChristophWurst** [comment]
> This requires us to store more of the IMAP state locally.

We have this since #2064

**Comment by kintaro1981** [comment]
recently I found two different solutions:
this is specific for roundbube but maybe can be usefull
https://github.com/toptensoftware/roundcube-snooze

this is another platform indipendent but a little more cumbersome:
https://github.com/kaosfere/snoozebox

**Comment by kintaro1981** [comment]
@ChristophWurst something is moving? :-)

**Comment by ChristophWurst** [comment]
Nothing our team is working on at the moment but if someone has time to contribute this feature we'd happily help to get it done.

**Comment by kintaro1981** [comment]
Here the implementation in cypht webmail.
https://github.com/jasonmunro/cypht/pull/659

**Comment by kintaro1981** [comment]
I'm saw that this is now in development. Finally I'm going to have another reason to leave gmail.

**Comment by ChristophWurst** [comment]
@nimishavijay @jancborchardt there are some stray specs for this feature at https://github.com/nextcloud/server/issues/39181#issuecomment-1641880618. Could you please write down how snooze/remind should work in Mail specifically?

My interpretation was that we do the real snooze feature first and move message between inboxes and dedicated *snooze* mailboxes. A background job moves the messages back when the snooze timer expired.

What role do Nextcloud notifications play for this feature? Are previously snoozed messages/threads sorted differently than regular messages?

**Comment by nimishavijay** [comment]
> My interpretation was that we do the real snooze feature first and move message between inboxes and dedicated snooze mailboxes. A background job moves the messages back when the snooze timer expired.

That is true! The 2 features where simply along the same lines of filing something away for later on. 

What you described is exactly what we had in mind as well. 
- [ ] the action menu of the mail has a "Snooze thread" action
- [ ] On clicking that a second level of actions come up, very similar to the "Send later" action menu while composing a message, except it says
  - < Snooze until
  - Tomorrow morning - 21 Jul 9:00 AM
  - Monday morning - 24 Jul 9:00 AM
  - Custom time
    [datetime picker] (nice-to-have)

@jancborchardt any preferences for the time? Gmail has tomorrow morning, this weekend, and next week. NC's send later has tomorrow morning, tomorrow afternoon and monday morning

![image](https://github.com/nextcloud/mail/assets/52440189/19943912-9ad1-4c6b-82a5-b5f53934dba8)

- [ ] If you click on any of the options the mail disappears from the inbox 
- [ ] there should be a "Snoozed" folder where the mail is now visible along with an icon on the right to indicate that it is snoozed, maybe the [schedule icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aschedule%3A)
- [ ] the snoozed mail can have all the usual actions as a regular mail in the 3 dot menu, except in the second level of actions when you click on snooze:
  - [ ] the active snooze option is the selected item
  - [ ]  there is an extra item at the end with the option "Unsnooze" 
- [ ] when the snooze time is reached, the mail appears at the top of the inbox with the snooze icon on the right (if the mail was unread when it was snoozed the icon can be on the left of the unread counter)

What do you think? :)

**Comment by kintaro1981** [comment]
In Gmail:

-  The snoozed email disappear from the inbox and go to the "postponed" folder, where instead of the original date/time is displayed the date (or the time if within today) to which the mail is postponed and is possibile to change date or disable it.
- The snoozed mail once the timer expire is displayed like it is just been delivered above the others and the date/time is bold and orange to make it more visible, once the mail is read it display the original date/time. I don't know what happens after some time, maybe is sorted back to its original date/time?

**Comment by ChristophWurst** [comment]
@JohannesGGE @jancborchardt ticket description updated with work packages and the MVP specs.

**Comment by jancborchardt** [comment]
Thanks @ChristophWurst! 2 questions / clarifications:
- "Snooze/Later mailbox created by user" – should be created automatically, not by users no?
- Part of the MVP should also be to make the unsnoozed mail be marked as unread, right?

**Comment by ChristophWurst** [comment]
I can imagine some people don't want us to create the mailbox automatically. Just like a lot of people don't like Mail to flag messages as important and have that flag show on other clients too.
The (automatically created) snooze mailbox will show on Thunderbird/K9. Some organizations use our Mail app to provision every Nextcloud user's email account. Even if someone never uses the Mail app, they will then suddenly see the mailbox.

We can brainstorm about this. For a MVP the automatic creation is not needed.

---

I don't know if marking as unread is common behavior for this feature. @JohannesGGE did you observe any such behavior with the other snooze implementations?

**Comment by JohannesGGE** [comment]
The behavior is not consistent regarding marking as unread. But most of the implementations do mark them as "was snoozed" in some way. So marking as unread is probably a good idea for the MVP.

**Comment by JohannesGGE** [comment]
Reopen because just the MVP is done.

**Comment by ChristophWurst** [comment]
All work packages have been done. Closing.
