### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by Quix0r** [nextcloud/mail#25]
Tagging messages as known from Thunderbird and many other mailer should be implemented. This allows easier handling of your messages. The user should be able to create additional "labels" or "tags" such as (but not limited).

Todo (must)
- [x] Read tags from IMAP and store them into our database #4665
- [x] Switch `$important` imap label to a `$label1` tag just like Thunderbird -> interoperability #4665
- [x] Add a one-time async background job that migrates old IMAP data from `$important` to `$label1` on IMAP (changes will automagically flow into our cache at the next sync)
- [x] Add a one-time async background job that pushes the local `flag_important` to IMAP (as `$label1`) for those server that support it, but also populate the tags table for all others
- [x] Handle reading a new message with no `$label1` on IMAP but a local label in the database -> this happens when permflags are not supported but the account was known before
- [x] https://github.com/nextcloud/mail/issues/4805 Display tags in the UI (assigned through Thunderbird)
- [x] https://github.com/nextcloud/mail/issues/4807 Allow user to assign default and custom tags
- [x] https://github.com/nextcloud/mail/issues/4806 Let the user configure additional tags (with label + color)

Todo (optionall follow-up, should possibly become a ticket when this one is closed)
* Add quick filtering for tags

**Comment by ChristophWurst** [comment]
do you know how that works on an IMAP level? Does the protocol support that?

**Comment by Quix0r** [comment]
I guess it cannot be done on server-side, maybe you can simulate it with some **X-NextCloud-Tags: bla, foo, bar** or so.

**Comment by ChristophWurst** [comment]
Hey there,

I'd just like to let you know that due to the [ongoing issue with Bountysource](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943) we're discussing ways to move to a different platform. As it looks right now, Bountysource might claim some of the money that was contributed by the community. We will try our best to prevent that. Historically we – the Nextcloud GmbH employees – simply put the claimed bounties back to other tickets until one was solved by a community member. So the money was always *from the community* and *for the community*. We'll therefore move to a better platform and currently don't post any new bounties until this situation is resolved. The current goal is to move/donate the money to [Nextcloud include](https://nextcloud.com/include/) but details will follow in the [forum post](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943).

Hope this makes sense. If you have any questions please ask them on the forum. This comment will be copy-pasted to all open issues with bounties.

Christoph and the Mail team

**Comment by ChristophWurst** [comment]
We decided that for the first basic version we'll store the flags primarily in Nextcloud's message cache, later on we will try to store them on IMAP additionally if IMAP support it.

**Comment by miaulalala** [comment]
A few thoughts:

- The sync for newly flagged messages works ( #4593 )
- There needs to be a new background migration job that syncs existing `ìmportant` flags before resetting the cache. To consider: looping over each mailbox and each message can be resource intensive, especially if a user has many mailboxes and/or many messages
- how will we handle servers that don't support permflags? The important flags should, if possible, not be lost when resetting the cache. Caching via flat file, or a table?

**Comment by miaulalala** [comment]
Some more thoughts:

- cross compatibility with other mail clients like Thunderbird, Outlook, Gmail, Rainloop, Roundcube, etc...
- keywords as mapped values with a new table (per user basis)
  - oc_mail_tags: uid, imap_keyword, display_name, color
  - this tag table could store the $important flags when migrating and resetting the cache, solving the issue of IMAP servers that don't support $PERFFLAGS 
- table oc_mail_message_tags: imap_message_id, tag_id
- tags with colour options
- some predefined labels like Thunderbird on first login, but they should be customisable

**Comment by miaulalala** [comment]
- default label color should depend on theming.

**Comment by miaulalala** [comment]
Possibly add the `$important` back to the tables `(mail_message, mail_message_tags`) with an optional repair step after migration for those servers that don't support `IMAP PERMANENTFLAGS`

**Comment by miaulalala** [comment]
Interesting to know for the colour options - Thunderbird assumes a priority ranking from 1 to 5 - so the BG colour is always chosen by highest priority

**Comment by ChristophWurst** [comment]
Info for later: https://github.com/nextcloud/mail/issues/25 adds the most crucial parts. We now read all tags from IMAP and store them int our DB. `$important` was replaced by `$label1` for compatibility with Thunerbird. Five default tags are created for every user, they are not editable right now.

I've added some todo to the original request description above.

**Comment by ChristophWurst** [comment]
@GretaD @miaulalala you did it!
