### ISSUE TITLE
One Click Suggested Unsubscribe

### ISSUE THREAD

**Issue by ChildLearningClub** [nextcloud/mail#5387]
## Feature Request

Easily unsubscribe to promotion emails by grouping them into a list and allowing for simple one click unsubscribe.

[Edison email](https://mail.edison.tech/) as well as apparently CleanFox have a feature to quickly unsubscribe to newsletters and promotional emails.

## Specification

* https://datatracker.ietf.org/doc/html/rfc2369
* https://datatracker.ietf.org/doc/html/rfc8058

## Work packages

- [x] https://datatracker.ietf.org/doc/html/rfc2369 https://github.com/nextcloud/mail/pull/8395
- [x] https://datatracker.ietf.org/doc/html/rfc2369 https://github.com/nextcloud/mail/pull/8434
- [ ] https://datatracker.ietf.org/doc/html/rfc8058 https://github.com/nextcloud/mail/pull/8438
- [x] https://github.com/nextcloud/documentation/issues/10015

**Comment by ChristophWurst** [comment]
I assume they get that info from some headers? Would you have an example email where that quick unsubscribe is shown so we can inspect the header info?

**Comment by philippstappert** [comment]
there is a `list-unsubscribe` header in most newsletters/mailing lists with a link to unsubscribe.

See RFC2369: https://datatracker.ietf.org/doc/html/rfc2369

**Comment by nimishavijay** [comment]
This is there in Gmail, Apple mail and Outlook so it sounds like a great idea!
As for how it looks on the frontend, something like this could work:
![image](https://user-images.githubusercontent.com/52440189/156173003-dfcb1685-ef2a-4149-8da8-887fa6489131.png)

Screenshots for other email clients are at [Penpot](https://design.penpot.app/#/workspace/464ebb90-b243-11eb-95bf-bcf80c3b5feb/c337d4c0-92fd-11ec-bd38-efdb6fa63305?page-id=e8226c50-9956-11ec-824f-49723f33a3ff&layout=assets)
cc @jancborchardt also

**Comment by ChristophWurst** [comment]
> there is a `list-unsubscribe` header in most newsletters/mailing lists with a link to unsubscribe.
> 
> See RFC2369: https://datatracker.ietf.org/doc/html/rfc2369

From testing and articles like https://www.sendinblue.com/blog/list-unsubscribe-header/ I learned that it's not always just a link. It might also be a `mailto:` address. HTTP links are easy to handle, so I quickly built https://github.com/nextcloud/mail/pull/8395. Mailto is a bit trickier. We need to either

1) Open the composer with the info from the mailto (like sender+subject prefilled)
2) Do 1) but submit the message to the outbox in the background
3) Do 1) but submit the message silently so it's neither shown in the outbox nor the *Sent* mailbox

**Comment by ChristophWurst** [comment]
I think I'll go with 2) because it's good UX and not as much magic as 3) should there be a reply to the background message

**Comment by nimishavijay** [comment]
> Submit the message to the outbox in the background

So the message will be seen in the Sent folder once it has been sent? That may lead to confusion since I'm assuming the contents of the mail would be fairly cryptic to an everyday user?

Also, since this is kind of a destructive action (once you unsubscribe from a mailing list it can be hard to subscribe again), there could be a confirmation dialogue `Unsubscribing will stop all messages from the mailing list [name of mailing list] [Cancel tertiary button] [Unsubscribe primary button]` Similar to Gmail (also cc @jancborchardt for wording here)

![image](https://user-images.githubusercontent.com/52440189/233615226-9a9bb9b2-8345-47ac-9069-0f85e329b004.png)

Also, interesting approach from Protonmail for messages which don't directly have an email for unsubscribing, but a link:

![image](https://user-images.githubusercontent.com/52440189/233615156-a017f373-68ed-48de-8101-8a6c475286f5.png)

This is the message shown when there is an email.

![image](https://user-images.githubusercontent.com/52440189/233616089-bc53e57a-c12e-4155-b6a7-432dc18a14d1.png)


Also, the mockup here conflicts with the the design in #8379 regarding showing the mail address in the message header. Suggestion: We show only the Unsubscribe button next to the mail address in the subline, without the "This message is from a mailing list" that is seen in the mockup here :)

**Comment by ChristophWurst** [comment]
> So the message will be seen in the Sent folder once it has been sent? That may lead to confusion since I'm assuming the contents of the mail would be fairly cryptic to an everyday user?

Not necessarily. It depends on the mailing list. Some just need a message with the subject "unsubscribe".

Even if the messages are slightly technical I would like my email client to be transparent about the messages sent. A message without traces is a bit meh.

**Comment by nimishavijay** [comment]
> Even if the messages are slightly technical I would like my email client to be transparent about the messages sent. A message without traces is a bit meh.

That's a great point! I am sold, nice :)

**Comment by ChristophWurst** [comment]
> One-click HTTP unsubscribe in accordance to https://datatracker.ietf.org/doc/html/rfc8058 (requires security work due to cross origin requests)

Tested this quickly and indeed run into ``Content Security Policy: The page’s settings blocked the loading of a resource at [https://list-unsubscribe.e](https://list-unsubscribe.eservice.emarsys.net/api/unsubscribe/288350551_2642574_3146670_du0M8qCKbw)``. This is not a problem for standalone email clients, of course. Moving to the server is also not an option as this would create *blind SSRF*.

**Comment by ChildLearningClub** [comment]
🎆
