### ISSUE TITLE
Dogfooding issues, from design glitches to missing functionality

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#7149]
Have been using the Mail app exclusively for the past few weeks, here are some findings.

@ChristophWurst @GretaD @karlitschek it is roughly sorted/prioritized as the top group is regressions and things related to the new design, while the bottom group is more missing features.

### Since the update to latest on tech-preview
- [ ] Long mails do not scroll anymore
- [ ] Active mails use border-radius-large, while hover/focus use border-radius-pill
- [ ] "more actions" button in message list does not have clear border on focus
- [ ] Unread indicator in left navigation
  - [ ] Does not line up with 3-dot-menu
  - [ ] Is displayed as dark (seems to be an issue with --color-primary-element-lighter)

### General
- [ ] Whitespace in the nav on top towards the header, and on the right between scrollbar and message list, and in settings scroll area to the right and bottom. Padding needs to be used instead of margin
- [ ] Settings button in bottom left does not use border-radius-pill
- [ ] Settings content area in bottom left has opaque background

### Writing
- [ ] Composer always uses topmost account as "From" identity instead of the one from currently open folder https://github.com/nextcloud/mail/issues/5060
- [ ] Opening the composer does not focus the "To" field anymore https://github.com/nextcloud/mail/issues/7125
- [ ] Putting something in the "To" field needs pressing enter or clicking the suggestion so it’s taken. Tabbing out or unfocusing the field should also accept what was put in as recipient.
- [ ] Drafts remain when message is sent https://github.com/nextcloud/mail/issues/4768

### Priority inbox
- [ ] The entry is called "Priority inbox" but the action and heading is called "Important". We should standardize this. Which one do you prefer?
  - [ ] We could keep "Priority inbox", then use "Priority" as heading, and "Priority"/"Not priority"
  - [ ] Or we go with "Important inbox", "Important" as heading, and keep "Important"/"Unimportant" for the actions.
- [ ] Mails shown in "Priority" repeat in the "Other" section below, but should not be duplicated.

### Message handling
- [ ] Archiving messages is manual https://github.com/nextcloud/mail/issues/22
- [ ] When marking message as spam, it is not directly deleted / moved to spam https://github.com/nextcloud/mail/issues/4101
- [ ] Multiselect menu missing "Mark as spam" and "Tags" https://github.com/nextcloud/mail/issues/7006
- [ ] Ability to empty spam/junk all at once https://github.com/nextcloud/mail/issues/6060

**Comment by ChristophWurst** [comment]
What version did you test with?

**Comment by jancborchardt** [comment]
> > Does not line up with 3-dot-menu
> 
> [nextcloud/nextcloud-vue#3178](https://github.com/nextcloud/nextcloud-vue/pull/3178) or is this about some other alignment?

Yes, it is actually that one, but see my comment: https://github.com/nextcloud/nextcloud-vue/pull/3178#issuecomment-1238179570

**Comment by meichthys** [comment]
It's really nice to see someone on the inside using mail as their daily driver. As a regular user myself, I can confirm that I've personally noticed most of the same issues/annoyances (I'm on  1.14.0-beta1).

A few issues that I'm surprised weren't listed are: #7036 and "Selecting message opens new browser tab" (perhaps this is fixed in the latest beta that is not available via the store yet).

**Comment by GretaD** [comment]
> It's really nice to see someone on the inside using mail as their daily driver. As a regular user myself, I can confirm that I regularly notice most of the same issues/annoyances (I'm on 1.14.0-beta1).
> 
> A few issues that I'm surprised weren't listed are: #7036 and "Selecting message opens new browser tab" (perhaps this is fixed in the latest beta that is not available via the store yet).

we have done couple of other pre-releases: https://github.com/nextcloud-releases/mail/releases

**Comment by meichthys** [comment]
Thanks @GretaD . I just udpated to the latest beta (https://github.com/nextcloud-releases/mail/tree/v1.14.0-beta3) and still seem the same issues i mentioned above. I don't currently see a way to upgrade to the v2.0 line of releases in Nextcloud 24. Is this possible without having to git clone the repo?

**Comment by GretaD** [comment]
Hello @meichthys, so sorry i missed you message. 
Are you still having this issue?

**Comment by meichthys** [comment]
Hi @GretaD, #7036 is still an issue for me, but the new-tab issue is fixed in 2.0.0-beta.6 👍

**Comment by jancborchardt** [comment]
Closing this issue as the majority of items have been fixed. When new problems come up, new issues should be created. :)
