### ISSUE TITLE
Followups to automatic out-of-office replies

### ISSUE THREAD

**Issue by st3iny** [nextcloud/mail#7173]
## TODO
- [x] https://github.com/nextcloud/mail/issues/7174 (ref https://github.com/nextcloud/mail/pull/7102#issuecomment-1235666461)
- [ ] https://github.com/nextcloud/mail/issues/7183 (ref https://github.com/nextcloud/mail/pull/7102#issuecomment-1235516347)
- [ ] https://github.com/nextcloud/mail/issues/7177 (ref https://github.com/nextcloud/mail/pull/7102#issuecomment-1235733513)
- [ ] https://github.com/nextcloud/mail/issues/7184 (ref
https://github.com/nextcloud/mail/pull/7102#issuecomment-1235765269)

## Maybe
- [ ] Remove marker from Subject and Message (ref https://github.com/nextcloud/mail/pull/7102#issuecomment-1235682045)

**Comment by ChristophWurst** [comment]
Could you please create separate tickets for these items? That makes it easier to track what's todo/in-progress/done.
