### ISSUE TITLE
Mention contacts in message body

### ISSUE THREAD

**Issue by hamza221** [nextcloud/mail#9432]
### Is your feature request related to a problem? Please describe.

As a user, I want to be able to mention contacts directly in the message body or in a reply and I want to be able to identify the messages I got mentioned in easily 

### Describe the solution you'd like

- [x] In message body mention contacts can be mentioned with @ symbol 
- [x] The contact gets added automatically to the "To" field
- [x] Mentions are rendered adequately in message envelope and preview text  
- [x] mailbox can be filtered/sorted for messages that mention you 

### Competitor Analysis
- Gmail inserts an anchorTag with a `mailto` href once clicked it opens a new message composer to the address 
- Outlook does the same but you can hover for quick actions and contact information (only for messages sent from outlook) 

### Work Package
- [x]  #10110
- [x]  #10111
- [x] #10112
- [x] https://github.com/nextcloud/documentation/issues/12170
