### ISSUE TITLE
Phishing detection

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#9453]
### Is your feature request related to a problem? Please describe.

As a Nextcloud Mail user, I want the app to help me detect phishing emails. Some of these phishing emails are not easy to spot.

### Describe the solution you'd like

Run some sanity checks on the email (to be brainstormed) and
1. Show a warning
2. Disable external links
3. Offer to move the message to spam

### Work packages
- [x] Research, brainstorming and goal definition
  - [x] Compare sender with sender label
  - [x] Trusted domains
  - [x] DKIM
  - [x] BIMI https://github.com/nextcloud/mail/pull/5784
- [x] Implementation
   - [x]  anchor tag text vs link checking #9994 
   - [x] Highlighting messages with a different reply-to #9610
   - [x] check full name address against contacts #9610
- [x] #9891
- [ ] Unit test for link checking https://github.com/nextcloud/mail/pull/10075
- [x] Admin docs if applicable (Not applicable) 
- [x] https://github.com/nextcloud/documentation/pull/12152

### Follow-up 

- [ ] Add a setting to disable HTML emails by default  
- [ ] Add quick actions (example: add email address to contact)
- [ ] Check emails for selectively applied CSS on forwards
context : https://www.schneier.com/blog/archives/2024/04/security-vulnerability-of-html-emails.html 

### Suggestion 
- [ ] Add a hint if a mail comes from an address that is neither in "contacts" nor has send any mails before. @kaffeeringe 

### Out of scope 
- resolving domain names
- Build a process to integrate against configurable Lists
- SPF 
- Preconfigured trust custom header tags 

### Describe alternatives you've considered

N/a

### Additional context

https://github.com/nextcloud/mail/issues/7864

**Comment by kaffeeringe** [comment]
Really important topic. I personally would like to get rid off all the fake DHL-notifications. But this is an essential feature for organisations.

**Comment by kaffeeringe** [comment]
Maybe add a hint if a mail comes from an address that is neither in "contacts" nor has send any mails before.
